# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0020_add_attribute_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='validation_end',
            field=models.DateField(blank=True, null=True, verbose_name='validation end'),
        ),
        migrations.AddField(
            model_name='function',
            name='validation_start',
            field=models.DateField(blank=True, null=True, verbose_name='validation start'),
        ),
        migrations.AddField(
            model_name='metadataversion',
            name='validation_end',
            field=models.DateField(blank=True, null=True, verbose_name='validation end'),
        ),
        migrations.AddField(
            model_name='metadataversion',
            name='validation_start',
            field=models.DateField(blank=True, null=True, verbose_name='validation start'),
        ),
    ]
